const hobbies_enum = [
  "singing",
  "reading",
  "dancing",
  "cooking",
  "travelling",
  "gaming",
  "painting",
  "photography",
  "writing",
  "cycling",
  "running",
  "yoga",
  "hiking",
  "swimming",
  "gardening",
  "fishing",
  "knitting",
  "drawing",
  "blogging",
  "coding",
  "baking",
  "watching movies",
  "DIY",
  "playing guitar",
  "playing piano",
  "martial arts",
  "chess",
  "bird watching",
  "surfing",
  "collecting stamps",
  "collecting coins",
  "makeup",
  "skateboarding",
  "snowboarding",
  "acting",
  "sculpting",
  "calligraphy",
  "jogging",
  "volunteering",
  "meditation",
  "language learning",
  "woodworking",
  "astronomy",
  "podcasting",
  "magic tricks",
  "scrapbooking",
  "karaoke",
  "puzzle solving",
  "RC car racing",
];

module.exports = hobbies_enum