name: Run Cron Jobs

on:
  schedule:
    - cron: '*/15 * * * *' 
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./HabiStreak/backend
        run: npm install

      - name: Run cron jobs
        working-directory: ./HabiStreak/backend
        run: node run-cron-jobs.js
